apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/showrav13/account-deployment.git
    targetRevision: main
    path: charts/finance-backend

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
